//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentiNovin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberingSystem {
            get {
                return ((int)(this["NumberingSystem"]));
            }
            set {
                this["NumberingSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPersianName {
            get {
                return ((bool)(this["ShowPersianName"]));
            }
            set {
                this["ShowPersianName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendSMS {
            get {
                return ((bool)(this["SendSMS"]));
            }
            set {
                this["SendSMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color ConditionColor {
            get {
                return ((global::System.Drawing.Color)(this["ConditionColor"]));
            }
            set {
                this["ConditionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color PlannedColor {
            get {
                return ((global::System.Drawing.Color)(this["PlannedColor"]));
            }
            set {
                this["PlannedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color CompletedColor {
            get {
                return ((global::System.Drawing.Color)(this["CompletedColor"]));
            }
            set {
                this["CompletedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short ToolBoxViewMode {
            get {
                return ((short)(this["ToolBoxViewMode"]));
            }
            set {
                this["ToolBoxViewMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Preventive/ Diagnostic</string>
  <string>Restorative/ Pedo</string>
  <string>Fixed/ Remove Prosth</string>
  <string>Endo/ Perio/ Surgery</string>
  <string>Conditions</string>
  <string>Common Services</string>
  <string>Other Services</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ToolTapCaptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ToolTapCaptions"]));
            }
            set {
                this["ToolTapCaptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal KhKCoeff {
            get {
                return ((decimal)(this["KhKCoeff"]));
            }
            set {
                this["KhKCoeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KhMedCenterCode {
            get {
                return ((string)(this["KhMedCenterCode"]));
            }
            set {
                this["KhMedCenterCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileType {
            get {
                return ((bool)(this["FileType"]));
            }
            set {
                this["FileType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CodingType {
            get {
                return ((bool)(this["CodingType"]));
            }
            set {
                this["CodingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisketteFilePath {
            get {
                return ((string)(this["DisketteFilePath"]));
            }
            set {
                this["DisketteFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CDDriverName {
            get {
                return ((string)(this["CDDriverName"]));
            }
            set {
                this["CDDriverName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PeriodSMS {
            get {
                return ((int)(this["PeriodSMS"]));
            }
            set {
                this["PeriodSMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMSText {
            get {
                return ((string)(this["SMSText"]));
            }
            set {
                this["SMSText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyToCD {
            get {
                return ((bool)(this["CopyToCD"]));
            }
            set {
                this["CopyToCD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MoKCoeff {
            get {
                return ((decimal)(this["MoKCoeff"]));
            }
            set {
                this["MoKCoeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MoMedCenterCode {
            get {
                return ((string)(this["MoMedCenterCode"]));
            }
            set {
                this["MoMedCenterCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal KhVisitPriceGeneral {
            get {
                return ((decimal)(this["KhVisitPriceGeneral"]));
            }
            set {
                this["KhVisitPriceGeneral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MoVisitPriceGeneral {
            get {
                return ((decimal)(this["MoVisitPriceGeneral"]));
            }
            set {
                this["MoVisitPriceGeneral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int KhVisitOrganPercent {
            get {
                return ((int)(this["KhVisitOrganPercent"]));
            }
            set {
                this["KhVisitOrganPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int MoVisitOrganPercent {
            get {
                return ((int)(this["MoVisitOrganPercent"]));
            }
            set {
                this["MoVisitOrganPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int KhOrganPercent {
            get {
                return ((int)(this["KhOrganPercent"]));
            }
            set {
                this["KhOrganPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int MoOrganPercent {
            get {
                return ((int)(this["MoOrganPercent"]));
            }
            set {
                this["MoOrganPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal KhVisitPriceSpecialist {
            get {
                return ((decimal)(this["KhVisitPriceSpecialist"]));
            }
            set {
                this["KhVisitPriceSpecialist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MoVisitPriceSpecialist {
            get {
                return ((decimal)(this["MoVisitPriceSpecialist"]));
            }
            set {
                this["MoVisitPriceSpecialist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MedCenterName {
            get {
                return ((string)(this["MedCenterName"]));
            }
            set {
                this["MedCenterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMedCenter {
            get {
                return ((bool)(this["IsMedCenter"]));
            }
            set {
                this["IsMedCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MultiColorDrawing {
            get {
                return ((bool)(this["MultiColorDrawing"]));
            }
            set {
                this["MultiColorDrawing"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS2008;AttachDbFilename=|DataDirectory|\\Data\\MNMDentiDB.mdf" +
            ";Integrated Security=True;Connect Timeout=60;User Instance=True")]
        public string MNMDentiDBConnectionString {
            get {
                return ((string)(this["MNMDentiDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Integrated Security=SSPI;Persist Security Info=False;User ID=sa;Initial Catalog=M" +
            "NMDentiDB;Data Source=.")]
        public string MNMDentiDBServerConnectionString {
            get {
                return ((string)(this["MNMDentiDBServerConnectionString"]));
            }
        }
    }
}
